handling of typing errors and telephone code prefix of countries added in drop down type
Mackewinsson/whatsapplinkbuilder pull request #4
Opened 2024-06-09 00:34 UTC by gervislm

Add error handling when writing a number so that the field returns feedback that must be a valid number if it is not provided, also a dropdown with country telephone code prefixes.

![Screenshot 2024-06-08 at 8 12 41 PM](https://github.com/Mackewinsson/whatsapplinkbuilder/assets/85653296/8744c322-d0b2-4cd0-83d9-bad391ccefeb)

![Screenshot 2024-06-08 at 8 12 56 PM](https://github.com/Mackewinsson/whatsapplinkbuilder/assets/85653296/7f4e2a04-c74f-4b65-b79e-d8bf465271ab)

![Screenshot 2024-06-08 at 8 13 04 PM](https://github.com/Mackewinsson/whatsapplinkbuilder/assets/85653296/c1d8e922-e25f-4fdf-b45c-b37d7c072781)

![Screenshot 2024-06-08 at 8 13 23 PM](https://github.com/Mackewinsson/whatsapplinkbuilder/assets/85653296/0696796a-727d-45db-8569-f13eee18e2bf)

2024-06-09 15:15 UTC, Mackewinsson requested changes

2024-06-09 15:15 UTC, Mackewinsson commented on src/components/FormComponent/index.js
> +  const [mustBeNumbers, setMustBeNumbers] = useState("Enter whatsapp number");
This should be a state that handles all errors in the future so dont call it this way. it should also be an object and the keys should be the field names

2024-06-09 17:54 UTC, gervislm commented
![Screenshot 2024-06-09 at 1 53 06 PM](https://github.com/Mackewinsson/whatsapplinkbuilder/assets/85653296/a315ab68-e432-41da-a54c-957f5fffcefe)

The state is declared as an object

2024-06-13 17:29 UTC, Mackewinsson approved these changes

2024-06-13 17:29 UTC, merged